import sys, json, time, os
import xlrd, xlwt, numpy
from customApi import General, dataUtils
from pathlib import Path

###########################################
###################ARGS####################
###########################################
## Source folder to get products files
sourcePath = sys.argv[1]
## Destiny folder to save products files parsed
destinyPath = sys.argv[2]

###########################################
###########ARGS CONTROL ERROR##############
###########################################
# Check source folder exists
if os.path.exists(sourcePath) == False:
  print("Folder {} does not exists".format(sourcePath))
  sys.exit(0)

# Check destiny folder exists
if os.path.exists(destinyPath) == False:
  print("Folder {} does not exists".format(destinyPath))
  sys.exit(0)

# Check folder has data
if len(os.listdir(sourcePath)) == 0:
  print("There is no files on folder {}".format(sourcePath))
  sys.exit(0)

###########################################
###############START PARSER################
###########################################
folderObject = Path(sourcePath)
destinyObject = Path(destinyPath)
## For each product
for product in folderObject.iterdir():
  ## get product name
  pr = (product.name).replace('.json','')
  ## Skip products which contains any letter
  ## This code aims to skip any possible character error
  ## Sometimes data generated by 'software' / 'PLC' could be wrong and
  ## insert some characters 
  try:
    float(pr)
  except:
    continue

  FinalMatrix = []
  ArrayYVectors = []
  matrix = General.read_json(product)
  ## Filter low samples
  ## Skip product that does not have more than 3 samples
  ## No useful data to be used afterwards
  if len(matrix) < 3:
    continue
  colX = dataUtils.getColumn(matrix, 0)
  colX = dataUtils.arrayToFloat(colX)
  normX = dataUtils.normVecSamples(colX) # Normalize X vector of time
  ## Calculate all Yvec interpolated ( Skip X vector )
  for i in range(1, len(matrix[0])):
    colY = dataUtils.getColumn(matrix, i)
    colY = dataUtils.arrayToFloat(colY)
    tabla = dataUtils.getTable(normX, colY) # Get interpolation table
    finalX, finalY = dataUtils.interpolation(tabla, 1) # Get Yvec interpolated from Xvec points
    ArrayYVectors.append(finalY)
  # Build matrix final for an specific product 
  for i in range(0, len(finalX)):
    RowFinalMatrix = []
    RowFinalMatrix.append(finalX[i])
    for vecY in ArrayYVectors:
      RowFinalMatrix.append(vecY[i])
    FinalMatrix.append(RowFinalMatrix)
  nameFile = destinyObject.joinpath(str(pr) + '-final.json')
  General.write_json(FinalMatrix,nameFile)

print("Matrix interpolated correctly")